#Archivo de configuración. Si no eres desarollador te recomendamos que no modifiques este archivo
#En su lugar emplea las opciones ingame. 

#Read-Write -> Ajustes de pantalla
[video]
    xres = 1920
    yres = 1080
    maxfps = 1000
    scale = 2
    fullscreen = 0
#Read-Write -> Volumen de sonido
[audio]

#Read-Write -> Controles
[input]

[gameplay]

#Read only -> Defines globales para el motor
[engine]
    title = "Unlighted"
    width = 256
    height = 144
    tile_size = 16

#Read only -> Rutas para los distintos recursos del juego
[PATH]
    assets_path = ../Assets/
    maps_path = ../Assets/maps/
    sounds_path = ../Assets/sounds/
    sprites_path = ../Assets/sprites/
    user_path = ../User/
    fonts_path = ../Assets/fonts

#Read only -> Opciones especiales para debug
[debug]
